"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mergeLineStyleMap = exports.mergeTextStyleMap = exports.splitTextStyleMap = exports.mergeInputBlockInfoMap = exports.splitLineStyleMap = exports.splitInputBlockInfoMap = exports.handleLineStyleShiftSelection = exports.getStyledLineMap = exports.getCurrentLineIndex = exports.handleTextStyleShiftSelection = exports.getClosestSelectionKey = exports.clearText = exports.inputBlockInfoMapToMarkdown = exports.mardownToInputBlockInfoMap = exports.getTextStyleSelectionsFromMarkdownText = exports.getLineStyle = exports.stringInsertAt = exports.stringReplaceAt = exports.getSelectionFromKey = exports.getKeyFromSelection = exports.getSelectionText = exports.useTextEditor = void 0;
var useTextEditor_1 = require("./useTextEditor");
Object.defineProperty(exports, "useTextEditor", { enumerable: true, get: function () { return useTextEditor_1.useTextEditor; } });
var utils_1 = require("./utils");
Object.defineProperty(exports, "getSelectionText", { enumerable: true, get: function () { return utils_1.getSelectionText; } });
Object.defineProperty(exports, "getKeyFromSelection", { enumerable: true, get: function () { return utils_1.getKeyFromSelection; } });
Object.defineProperty(exports, "getSelectionFromKey", { enumerable: true, get: function () { return utils_1.getSelectionFromKey; } });
Object.defineProperty(exports, "stringReplaceAt", { enumerable: true, get: function () { return utils_1.stringReplaceAt; } });
Object.defineProperty(exports, "stringInsertAt", { enumerable: true, get: function () { return utils_1.stringInsertAt; } });
Object.defineProperty(exports, "getLineStyle", { enumerable: true, get: function () { return utils_1.getLineStyle; } });
Object.defineProperty(exports, "getTextStyleSelectionsFromMarkdownText", { enumerable: true, get: function () { return utils_1.getTextStyleSelectionsFromMarkdownText; } });
Object.defineProperty(exports, "mardownToInputBlockInfoMap", { enumerable: true, get: function () { return utils_1.mardownToInputBlockInfoMap; } });
Object.defineProperty(exports, "inputBlockInfoMapToMarkdown", { enumerable: true, get: function () { return utils_1.inputBlockInfoMapToMarkdown; } });
Object.defineProperty(exports, "clearText", { enumerable: true, get: function () { return utils_1.clearText; } });
Object.defineProperty(exports, "getClosestSelectionKey", { enumerable: true, get: function () { return utils_1.getClosestSelectionKey; } });
Object.defineProperty(exports, "handleTextStyleShiftSelection", { enumerable: true, get: function () { return utils_1.handleTextStyleShiftSelection; } });
Object.defineProperty(exports, "getCurrentLineIndex", { enumerable: true, get: function () { return utils_1.getCurrentLineIndex; } });
Object.defineProperty(exports, "getStyledLineMap", { enumerable: true, get: function () { return utils_1.getStyledLineMap; } });
Object.defineProperty(exports, "handleLineStyleShiftSelection", { enumerable: true, get: function () { return utils_1.handleLineStyleShiftSelection; } });
Object.defineProperty(exports, "splitInputBlockInfoMap", { enumerable: true, get: function () { return utils_1.splitInputBlockInfoMap; } });
Object.defineProperty(exports, "splitLineStyleMap", { enumerable: true, get: function () { return utils_1.splitLineStyleMap; } });
Object.defineProperty(exports, "mergeInputBlockInfoMap", { enumerable: true, get: function () { return utils_1.mergeInputBlockInfoMap; } });
Object.defineProperty(exports, "splitTextStyleMap", { enumerable: true, get: function () { return utils_1.splitTextStyleMap; } });
Object.defineProperty(exports, "mergeTextStyleMap", { enumerable: true, get: function () { return utils_1.mergeTextStyleMap; } });
Object.defineProperty(exports, "mergeLineStyleMap", { enumerable: true, get: function () { return utils_1.mergeLineStyleMap; } });
