export type {
  PlatformMode,
  Selection,
  LineStyle,
  TextStyle,
  SelectionKey,
  LineKey,
  TextStyleMap,
  LineStyleMap,
  TextInfo,
  TextBlockInfo,
  ImageBlockInfo,
  InputBlockInfo,
  InputBlockInfoMap,
  StyledText,
  StyledLine,
  StyledLineMap,
  LINE_TAGS,
  TEXT_TAGS,
} from "./types";
export { useTextEditor } from "./useTextEditor";
export {
  getSelectionText,
  getKeyFromSelection,
  getSelectionFromKey,
  stringReplaceAt,
  stringInsertAt,
  getLineStyle,
  getTextStyleSelectionsFromMarkdownText,
  mardownToInputBlockInfoMap,
  inputBlockInfoMapToMarkdown,
  clearText,
  getClosestSelectionKey,
  handleTextStyleShiftSelection,
  getCurrentLineIndex,
  getStyledLineMap,
  handleLineStyleShiftSelection,
  splitInputBlockInfoMap,
  splitLineStyleMap,
  mergeInputBlockInfoMap,
  splitTextStyleMap,
  mergeTextStyleMap,
  mergeLineStyleMap,
} from "./utils";
